# AWS CodeBuild buildspec to build the nginx alpine image
# By Jason Umiker (jason.umiker@gmail.com)

# This requires the following environment variables be set on the Project:
# AWS_DEFAULT_REGION (Supplied by CodeBuild)
# AWS_ACCOUNT_ID
# IMAGE_REPO_NAME
# IMAGE_TAG
# SERVICE_NAME

version: 0.2

phases:
  pre_build:
    commands:
      - CODEBUILD_RESOLVED_SOURCE_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:-$IMAGE_TAG}"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg STAGE=$STAGE  --build-arg REGION=$REGION --build-arg stack=$stack  -t cf-$SERVICE_NAME -f CF.Dockerfile .
      - docker build --build-arg STAGE=$STAGE  --build-arg REGION=$REGION --build-arg stack=$stack  -t $SERVICE_NAME -f Dockerfile .
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Build stage successfully completed on `date`
      - echo Run the Docker image...
      - docker run  --rm -e stack=$stack  -e STAGE=$STAGE -e REGION=$REGION cf-$SERVICE_NAME
      - docker run  --rm -e stack=$stack  -e STAGE=$STAGE -e REGION=$REGION  $SERVICE_NAME
      - printf '[{"name":"%s","imageUri":"%s"}]' "$SERVICE_NAME" "$IMAGE_URI" > "$SERVICE_NAME"-images.json
artifacts:
  files: $SERVICE_NAME-images.json