AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  serverlesspy:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::760144776757:role/service-role/serverless-py-role-a6x14aia'
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 10
        Api1:
          Type: Api
          Properties:
            Path: /serverless-py
            Method: ANY
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
